[project]
name = "notion-finance-streamlit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "notion-client>=2.7.0",
    "pandas>=2.3.3",
    "plotly>=6.4.0",
    "streamlit>=1.51.0",
]
